server:
  port: 9001

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: orderHistoryGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://localhost:8081
        specific:
          avro:
            reader: true
#        spring:
#          json:
#            trusted:
#              packages: '*'

avro:
  topic:
    name: spring.boot.order.history.avro.topic.v1