server:
  port: 9000

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        schema:
          registry:
            url: http://localhost:8081
        spring:
          json:
            add:
              type:
                headers: 'false'

avro:
  topic:
    name: spring.boot.order.history.avro.topic.v1